lits/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :admin, path: 'topsecret' do
    resources :sources
    root to: 'index#index'
  end

  resources :events, only: [:index, :show] do
    get 'index(/:page)', to: 'events#index', on: :collection
    get 'date/:date', to: 'events#date', on: :collection, as: :events_date
  end

  resources :tags, only: [:index, :show] do
    get ':id(/:page)', to: 'tags#show', on: :collection
  end

  patch 'feed/:id', to: 'users#update', as: :feed_update
  get 'feed/edit', to: 'users#edit', as: :user_edit

  get 'search', to: 'search#index'
  get 'search(/:q)', to: 'search#search', as: :search_query

  get 'category/:category_id(/:page)', to: 'categories#show', as: :category

  root 'events#index'
end

lits/app/models/source.rb
class Source < ApplicationRecord
  belongs_to :source_type
  belongs_to :city
  has_many :events, dependent: :destroy
  validates :ref, presence: true, url: true, uniqueness: true
  validates :ext_id, numericality: true, uniqueness: true
end

lits/app/models/source_type.rb
class SourceType < ApplicationRecord
  KEYS = { vk: 1, fb: 2, dou: 3 }.freeze
  NAMES = { 1 => :vk, 2 => :fb, 3 => :dou }.freeze
end

lits/app/controllers/admin/sources_controller.rb
module Admin
  class SourcesController < BaseController
    # before_action :url_analyzer, only: [:update, :create]

    def create
      @source = Source.new(source_params)
      ref = source_params[:ref]
      url_analyzer(ref) unless ref.empty?

      if @source.save
        flash[:notice] = 'Source was successfully created.'
        redirect_to action: 'index'
      else
        flash[:error] = 'Source not created! ' + @source.errors.full_messages.to_sentence + @error
        render action: 'new'
      end
    end

    def edit
    end

    def update
      ref = source_params[:ref]
      url_analyzer(ref) unless ref.empty?

      if @source.update(source_params)
        flash[:notice] = 'Source was successfully updated.'
        redirect_to admin_sources_path
      else
        flash[:error] = 'Source not updated! ' + @source.errors.full_messages.to_sentence + @error
        render action: 'edit'
      end
    end

    private

    def url_analyzer(uri)
      fresh_source = URI.parse(uri.gsub(/\s+/, ''))
      # FIXME
      unless fresh_source.scheme.casecmp('https').zero?
        @error += ' Scheme must be HTTPS!'
        return
      end
      group = fresh_source.path.delete('/')
      case fresh_source.host.sub('www.', '')
      when 'facebook.com', 'fb.com'
        @source.source_type_id = source_type(:fb)
        @source.ext_id = fb_ext_id(group)
      when 'vk.com', 'm.vk.com'
        @source.source_type_id = source_type(:vk)
        @source.ext_id = vk_ext_id(group)
      when 'dou.ua'
        @source.source_type_id = source_type(:dou)
        # fake ext_id for dou to pass model validation
        @source.ext_id = DateTime.now.to_i
      else
        @error += 'Unknown Source' && return
      end
    end

    def fb_ext_id(group)
      oauth = Koala::Facebook::OAuth.new
      @graph = Koala::Facebook::API.new(oauth.get_app_access_token)
      begin
        @graph.get_object(group)['id']
      rescue Koala::Facebook::ClientError => e
        @error += " FB validation: #{e.message}"
      end
    end

    def vk_ext_id(group)
      @client = VkontakteApi::Client.new
      begin
        @client.groups.getById(group_id: group).last['gid']
      rescue StandardError => e
        @error += " VK validation: #{e.message}"
      end
    end

    def source_type(name)
      source = SourceType.pluck(:name, :id).to_h.symbolize_keys
      source[name]
    end

    def source_params
      @error = ''
      params.require(:source).permit :source_type_id,
                                     :ref,
                                     :created_at,
                                     :updated_at,
                                     :ext_id,
                                     :city_id
    end
  end
end

lits/app/helpers/admin/sources_helper.rb
module Admin::SourcesHelper
  def filtered_source
    SourceType.where.not(name: :dou)
  end

  def cities
    City.all
  end

end

lits/app/views/admin/sources/_form.html.erb
<%= simple_form_for([:admin, @source]) do |f| %>
  <%= f.error_notification %>
  <%#= f.input :source_type_id, collection: filtered_source, prompt: false %>
  <%= f.input :ref, type: :url, as: :string %>
  <%#= f.url_field(:ref, :string)  %>
  <%#= f.input :ext_id %>
  <%= f.input :city_id, collection: cities, prompt: false %>
  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

<hr>

lits/app/views/admin/sources/edit.html.erb
<h1>Editing Source</h1>

<div class="col-md-6">
<%= render 'form', source: @source %>
<%= link_to 'Back', admin_sources_path, class: 'btn btn-primary' %>
</div>

lits/app/views/admin/sources/index.html.erb
<h1>Sources</h1>

<%= link_to 'New Source', new_admin_source_path, class: 'btn btn-primary' %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <td style="width: 30px;" class="col-md-1">Source</td>
      <td style="max-width: 300px; width: 300px; word-wrap: break-word;" class="col-md-5">Reference URL</td>
      <td class="col-md-2">Source ext_id</td>
      <td class="col-md-2">City</td>
      <th colspan="3" class="col-md-2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.source_type.name %></td>
        <td style="max-width: 600px; width: 600px; word-wrap: break-word;"><%= source.ref %></td>
        <td><%= source.ext_id %></td>
        <td><%= source.city.name %></td>
        <td><%= link_to 'Show', admin_source_path(source), class: 'btn btn-xs btn-info' %></td>
        <td><%= link_to 'Edit', edit_admin_source_path(source), class: 'btn btn-xs btn-warning' %></td>
        <td><%= link_to 'Destroy',
                        admin_source_path(source),
                        method: :delete,
                        data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

lits/app/views/admin/sources/new.html.erb
<h1>New Source</h1>

<div class="col-md-6">
<%= render 'form', source: @source %>
<%= link_to 'Back', admin_sources_path, class: 'btn btn-primary' %>
</div>

lits/app/views/admin/sources/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
	    	<td>source_type_id</td>
	      	<td style="max-width: 300px; width: 300px; word-wrap: break-word;">ref</td>
	      	<td>ext_id</td>
	      	<td>city</td>
	    </tr>
	</thead>
	<tbody>
		<tr>
	        <td><%= @source.source_type_id %></td>
	        <td style="max-width: 300px; width: 300px; word-wrap: break-word;"><%= @source.ref %></td>
	        <td><%= @source.ext_id %></td>
	        <td><%= @source.city.name %></td>
	    <tr>
	</tbody>
</table>
<%= link_to 'Edit', edit_admin_source_path(@source), class: 'btn btn-primary' %>
<%= link_to 'Back', admin_sources_path, class: 'btn btn-primary' %>